config/routes.rb
Rails.application.routes.draw do
  get '/products/favorites' => 'products#favorites'

  resources :categories
  resources :product_categories
  resources :interests
  resources :bids
  resources :products
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get '/home' => 'welcome#home'
  # Defines the root path route ("/")
  root "products#index"

end

app/models/bid.rb
class Bid < ApplicationRecord
    belongs_to :product
    belongs_to :user

    validates :user_id, presence: true
    def self.trending_products
        Bid.all.sort_by(&:created_at).reverse.first(10)
    end

   
end 

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :require_logged_in, :set_bid, only: %i[ show edit update destroy ]
  

  # GET /bids or /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1 or /bids/1.json
  def show
    @bid = Bid.find(params[:id])
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # POST /bids or /bids.json
  def create
    @bid = Bid.new(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to product_path(@bid.product), notice: "#{current_user.name} bidded #{@bid.price} for #{@bid.product.name}." }
        format.json { render :show, status: :created, location: @bid }
      else
        if logged_in?
          format.html { redirect_to product_path(@bid.product), notice: "Please put the bid amount!" }
          format.json { render json: @bid.errors, status: :unprocessable_entity }
        else
          format.html { redirect_to product_path(@bid.product), notice: "Please log in first!" }
          format.json { render json: @bid.errors, status: :unprocessable_entity }
        end
        end
    end
  end

  # PATCH/PUT /bids/1 or /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to bid_url(@bid), notice: "Bid was successfully updated." }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1 or /bids/1.json
  def destroy
    @bid.destroy

    respond_to do |format|
      format.html { redirect_to bids_url, notice: "Bid was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bid_params
      params.require(:bid).permit(:price, :product_id, :user_id)
    end
end

app/views/bids/_bid.html.erb
<div id="<%= dom_id bid %>">
  <p>
    <strong>Price:</strong>
    <%= bid.price %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= bid.product.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= bid.user.name %>
  </p>

  <p>
    <strong>Placed:</strong>
    <%= bid.created_at%>
  </p>

</div>

app/views/bids/_form.html.erb
<%= form_with(model: bid) do |form| %>
  <% if bid.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
        <% bid.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.number_field :product_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bids/index.html.erb
<body class = "h-full bg-gradient-to-b from-yellow-100 to-blue-400 overscroll-none text-center">

  <div class = "mx-auto w-full">
    <header class = "bg-blue-400 font-bold p-3">

        <div class= "p-2">
          <ul class = "list-none text-center mx-auto">
            <h1 class = "text-4xl no-underline text-green-400"><%= link_to "KɪᴄᴋᴇᴅOғғEʙᴀʏ🏠", '/'%></h1>
            <h2 class = "mx-auto text-2xl">Because ➡️➡️➡️➡️ Everyone🫵 Deserves💪 a Second♻️ Chance😇</h2>
                <% if logged_in? %>
            <h3 class = "text 2xl">Hello! <%=current_user.name %></h3><br>
              <a href="/home">  
              <button>My profile</button></a>
              <a href="/logout">  
              <button>Logout</button></a> 
            <% else %>
              <a href="/login">  
              <button class= "text-2xl rounded-none hover:rounded-full">Login</button></a>
              <a href="/users/new">  
              <button class= "text-2xl rounded-none hover:rounded-full">Sign Up</button></a> 
            <% end %>
              <h3 class = "mx-auto text-2xl">🔎🅢🅔🅐🅡🅒🅗🔎</h3>
              <%= form_tag(products_path, method: :get) do %>
              <%= text_field_tag(:search, params[:search])%>
              <%end%>
          </ul>
        </div>

      </header>

    <div>
      <h1 class = "text-5xl underline">Bid$</h1>

      <div class = "text-3xl" id="bids">
        <% @bids.each do |bid| %>
          <div class = "p-2">
              <%= render bid %>
              <p>
                <%= link_to "Show this bid", bid %>
              </p>
            <% end %>
          </div>

      </div>

  </div>
</body>

app/views/bids/new.html.erb
<h1>New bid</h1>

<%= render "form", bid: @bid %>

<br>

<div>
  <%= link_to "Back to bids", bids_path %>
</div>

app/views/bids/show.html.erb
<body  class = "h-screen bg-gradient-to-b from-yellow-100 to-blue-400 overscroll-none text-center">
  <p style="color: green"><%= notice %></p>
  <div>
      <div class= "p-2">
        <ul class = "list-none text-center mx-auto">
          <h1 class = "text-4xl no-underline text-green-400"><%= link_to "KɪᴄᴋᴇᴅOғғEʙᴀʏ🏠", '/'%></h1>
          <h2 class = "mx-auto text-2xl">Because ➡️➡️➡️➡️ Everyone🫵 Deserves💪 a Second♻️ Chance😇</h2>
              <% if logged_in? %>
          <h3 class = "text 2xl">Hello! <%=current_user.name %></h3><br>
            <a href="/home">  
            <button>My profile</button></a>
            <a href="/logout">  
            <button>Logout</button></a> 
          <% else %>
            <a href="/login">  
            <button class= "text-2xl rounded-none hover:rounded-full">Login</button></a>
            <a href="/users/new">  
            <button class= "text-2xl rounded-none hover:rounded-full">Sign Up</button></a> 
          <% end %>
            <h3 class = "mx-auto text-2xl">🔎🅢🅔🅐🅡🅒🅗🔎</h3>
            <%= form_tag(products_path, method: :get) do %>
            <%= text_field_tag(:search, params[:search])%>
            <%end%>
        </ul>
      </div>
    <h1 class = "text-5xl underline">Bid</h1>
    <%= render @bid %>

    <div>
      <%= link_to "Back to bids", bids_path %> | 
      <%= link_to "Back to #{@bid.product.name}", @bid.product%>
    </div>
  </div>
</body>