config/routes.rb
Rails.application.routes.draw do
  get '/products/favorites' => 'products#favorites'

  resources :categories
  resources :product_categories
  resources :interests
  resources :bids
  resources :products
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get '/home' => 'welcome#home'
  # Defines the root path route ("/")
  root "products#index"

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :interests
    has_many :product_categories
    has_many :products, through: :product_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<body class =  "h-full bg-gradient-to-b from-yellow-100 to-blue-400 overscroll-none items-center">

  <div class = "mx-auto text-center">
    <header class = "bg-blue-400 font-bold p-3 col-start-1 col-span-6 mx-auto">
      <div class= "p-2">
        <ul class = "list-none text-center mx-auto">
          <h1 class = "text-4xl no-underline text-green-400"><%= link_to "KɪᴄᴋᴇᴅOғғEʙᴀʏ🏠", '/'%></h1>
          <h2 class = "mx-auto text-2xl">Because ➡️➡️➡️➡️ Everyone🫵 Deserves💪 a Second♻️ Chance😇</h2>
              <% if logged_in? %>
          <h3 class = "text 2xl">Hello! <%=current_user.name %></h3><br>
            <a href="/home">  
            <button>My profile</button></a>
            <a href="/logout">  
            <button>Logout</button></a> 
          <% else %>
            <a href="/login">  
            <button class= "text-2xl rounded-none hover:rounded-full">Login</button></a>
            <a href="/users/new">  
            <button class= "text-2xl rounded-none hover:rounded-full">Sign Up</button></a> 
          <% end %>
            <h3 class = "mx-auto text-2xl">🔎🅢🅔🅐🅡🅒🅗🔎</h3>
            <%= form_tag(products_path, method: :get) do %>
            <%= text_field_tag(:search, params[:search])%>
            <%end%>
        </ul>
      </div>
    </header>
    <h1 class = "text-6xl text-blue-400"><%=@category.name.titleize%></h1>
    <ul class = "list-none text-4xl"><%@category.products.each do |p|%>
      <li>🔥 <%=link_to p.name, p%></li>
        <ul class = "list-none">
          <li>💰Current Bid <%=p.max_bid_price%></li>
        </ul><br>
      <%end%>
    </ul>

    </div>
  </div>
</body>